version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-service 
    ports:
      - 8888:8888
    env_file: .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /tmp/mongo:/data/db
    ports:
      - 27017:27017
